python: fix the dependency
There are two recipes for python-editor:
 * meta-cloud-services/meta-openstack: python-python-editor 0.4.0
 * meta-openembedded/meta-python: python-editor 1.0.3

use the one with newer version in meta-python to avoid confilcts:
Error: Transaction check error:
  file /usr/lib/python2.7/site-packages/editor.py conflicts between
  attempted installs of
  python-python-editor-0.4+git0+d6fa2a6bb3-r0.corei7_64 and
  python-editor-1.0.3-r0.corei7_64
    file /usr/lib/python2.7/site-packages/editor.pyc conflicts between
    attempted installs of
    python-python-editor-0.4+git0+d6fa2a6bb3-r0.corei7_64 and
    python-editor-1.0.3-r0.corei7_64

fix #56

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>