packagegroup-akraino: add caas-kubernetes and caas-danm
Add caas-kubernetes and caas-danm and remove kubernetes and cni.

Error: Transaction check error:
  file /usr/bin/kubectl conflicts between attempted installs of caas-kubernetes-1.15.2+1-r0.corei7_64 and kubectl-1.13.5+git2166946f41b36dea2c4626f90a77706f426cdea2-r0.corei7_64
  file /usr/bin/kubelet conflicts between attempted installs of kubelet-1.13.5+git2166946f41b36dea2c4626f90a77706f426cdea2-r0.corei7_64 and caas-kubernetes-1.15.2+1-r0.corei7_64
  file /opt/cni/bin/bridge conflicts between attempted installs of caas-danm-4.0.0+2-r0.corei7_64 and cni-0.6.0+gitcc562d1b44b3d00b8c341250d49a8a0823a1c085-r0.corei7_64
  file /opt/cni/bin/dhcp conflicts between attempted installs of caas-danm-4.0.0+2-r0.corei7_64 and cni-0.6.0+gitcc562d1b44b3d00b8c341250d49a8a0823a1c085-r0.corei7_64
  file /opt/cni/bin/flannel conflicts between attempted installs of caas-danm-4.0.0+2-r0.corei7_64 and cni-0.6.0+gitcc562d1b44b3d00b8c341250d49a8a0823a1c085-r0.corei7_64
  file /opt/cni/bin/host-device conflicts between attempted installs of caas-danm-4.0.0+2-r0.corei7_64 and cni-0.6.0+gitcc562d1b44b3d00b8c341250d49a8a0823a1c085-r0.corei7_64
  file /opt/cni/bin/host-local conflicts between attempted installs of caas-danm-4.0.0+2-r0.corei7_64 and cni-0.6.0+gitcc562d1b44b3d00b8c341250d49a8a0823a1c085-r0.corei7_64
  file /opt/cni/bin/loopback conflicts between attempted installs of caas-danm-4.0.0+2-r0.corei7_64 and cni-0.6.0+gitcc562d1b44b3d00b8c341250d49a8a0823a1c085-r0.corei7_64
  file /opt/cni/bin/macvlan conflicts between attempted installs of caas-danm-4.0.0+2-r0.corei7_64 and cni-0.6.0+gitcc562d1b44b3d00b8c341250d49a8a0823a1c085-r0.corei7_64
  file /opt/cni/bin/ptp conflicts between attempted installs of caas-danm-4.0.0+2-r0.corei7_64 and cni-0.6.0+gitcc562d1b44b3d00b8c341250d49a8a0823a1c085-r0.corei7_64
  file /opt/cni/bin/tuning conflicts between attempted installs of caas-danm-4.0.0+2-r0.corei7_64 and cni-0.6.0+gitcc562d1b44b3d00b8c341250d49a8a0823a1c085-r0.corei7_64
  file /opt/cni/bin/vlan conflicts between attempted installs of caas-danm-4.0.0+2-r0.corei7_64 and cni-0.6.0+gitcc562d1b44b3d00b8c341250d49a8a0823a1c085-r0.corei7_64

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>