access-management/config-manager: fix the dir permission
Fixed the issue:
Error: Transaction check error:
  file /lib/systemd/system conflicts between attempted installs of config-manager-c25.50946f8-r0.corei7_64 and volatile-binds-1.0-r0.noarch
  file /lib/systemd/system conflicts between attempted installs of ceph-13.2.2-r0.corei7_64 and config-manager-c25.50946f8-r0.corei7_64
  file /lib/systemd/system conflicts between attempted installs of access-management-c4.34040e0-r0.corei7_64 and lxdm-1:0.5.3-r0.corei7_64
  file /lib/systemd/system conflicts between attempted installs of sysklogd-1.5.1-r0.corei7_64 and access-management-c4.34040e0-r0.corei7_64

fix #56

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>