mailcap: fix the conflicts with nginx
Fixed the following conflicts:
Error: Transaction check error:
  file /etc/nginx/mime.types conflicts between attempted installs of
  mailcap-2.1.48-r0.corei7_64 and nginx-1.15.2-r0.corei7_64

fix #31

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>